name: Deploy projeto CRUD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
        
      - name: Build project
        run: cd CRUD-BACK && mvn clean install -DskipTests
      
      - name: Login Docker Hub
        run: docker login -u jntcruz -p jonatas123

      - name: Build docker image
        run: docker build -t jntcruz/javadb .
      - name: Push image docker
        run: docker push jntcruz/javadb
  
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: pull image
        run: sudo docker pull jntcruz/javadb:latest
      - name: Remove docker image
        run: sudo docker rm -f javadb
      - name: run docker container
        run: sudo docker run -d -p 8080:8080 --name javadb jntcruz/javadb:latest